services:
  valkey:
    image: valkey/valkey
    container_name: valkey-server
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data/valkey

  pg:
    image: postgres:16-alpine
    container_name: pg-server
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/data/db'

  pgadmin:
    container_name: pg-admin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@app.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_PORT=54321
    ports:
      - "4321:80"
    depends_on:
      - pg
    logging:
      driver: none
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data:
  valkey_data:
  pgadmin_data:
