name: CI with Codecov
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    environment: test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ${{ env.NODE_ENV }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      VALKEY_URL: ${{ secrets.VALKEY_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_ISSUER: ${{ env.JWT_ISSUER }}
      JWT_AUDIENCE: ${{ env.JWT_AUDIENCE }}
      JWT_ACCESS_EXPIRATION_MINUTES: ${{ env.JWT_ACCESS_EXPIRATION_MINUTES }}
      JWT_REFRESH_EXPIRATION_DAYS: ${{ env.JWT_REFRESH_EXPIRATION_DAYS }}
      JWT_RESET_PASSWORD_EXPIRATION_MINUTES: ${{ env.JWT_RESET_PASSWORD_EXPIRATION_MINUTES }}
      JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: ${{ env.JWT_VERIFY_EMAIL_EXPIRATION_MINUTES }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      EMAIL_FROM: ${{ env.EMAIL_FROM }}
    services:
      valkey:
        image: valkey/valkey
        ports:
          - 6379:6379
      database:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: pnpm install
      - name: Migrate db
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm migrate:dev -- --skip-seed
      - name: Run Vitest with coverage
        run: pnpm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info,./coverage/cobertura-coverage.xml
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
